# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotos', '0002_auto_20180504_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_title',
            new_name='title',
        ),
    ]
