# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrophotos', '0003_auto_20180506_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
